#!/bin/sh
set -eu

require_environment() {
  variable_name="$1"
  eval "variable_value=\${${variable_name}:-}"
  if [ -z "$variable_value" ]; then
    echo "Required DB-000 test environment variable is missing: $variable_name" >&2
    exit 64
  fi
}

for variable_name in \
  POSTGRES_HOST \
  POSTGRES_PORT \
  POSTGRES_DB \
  SUPPORT_OWNER_PASSWORD \
  COMMERCE_OWNER_PASSWORD \
  SUPPORT_APP_PASSWORD \
  COMMERCE_APP_PASSWORD
do
  require_environment "$variable_name"
done

psql_as() {
  role_name="$1"
  role_password="$2"
  shift 2
  PGPASSWORD="$role_password" psql \
    --no-psqlrc \
    --quiet \
    --set ON_ERROR_STOP=1 \
    --host "$POSTGRES_HOST" \
    --port "$POSTGRES_PORT" \
    --username "$role_name" \
    --dbname "$POSTGRES_DB" \
    "$@"
}

expect_denied() {
  role_name="$1"
  role_password="$2"
  statement="$3"
  if psql_as "$role_name" "$role_password" --command "$statement" >/dev/null 2>&1; then
    echo "Expected database permission denial for role: $role_name" >&2
    exit 1
  fi
}

cleanup() {
  psql_as support_owner "$SUPPORT_OWNER_PASSWORD" \
    --command 'DROP TABLE IF EXISTS support.__db000_grant_probe' >/dev/null 2>&1 || true
  psql_as commerce_owner "$COMMERCE_OWNER_PASSWORD" \
    --command 'DROP TABLE IF EXISTS commerce.__db000_grant_probe' >/dev/null 2>&1 || true
}
trap cleanup EXIT HUP INT TERM

psql_as support_owner "$SUPPORT_OWNER_PASSWORD" --file /db/tests/assert-catalog.sql

psql_as support_owner "$SUPPORT_OWNER_PASSWORD" --command \
  'CREATE TABLE support.__db000_grant_probe (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, value text NOT NULL)'
psql_as commerce_owner "$COMMERCE_OWNER_PASSWORD" --command \
  'CREATE TABLE commerce.__db000_grant_probe (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, value text NOT NULL)'

psql_as support_app "$SUPPORT_APP_PASSWORD" --command \
  "INSERT INTO support.__db000_grant_probe (value) VALUES ('support'); SELECT count(*) FROM support.__db000_grant_probe; UPDATE support.__db000_grant_probe SET value = 'updated'; DELETE FROM support.__db000_grant_probe"
psql_as commerce_app "$COMMERCE_APP_PASSWORD" --command \
  "INSERT INTO commerce.__db000_grant_probe (value) VALUES ('commerce'); SELECT count(*) FROM commerce.__db000_grant_probe; UPDATE commerce.__db000_grant_probe SET value = 'updated'; DELETE FROM commerce.__db000_grant_probe"

expect_denied commerce_app "$COMMERCE_APP_PASSWORD" \
  'SELECT * FROM support.__db000_grant_probe'
expect_denied support_app "$SUPPORT_APP_PASSWORD" \
  'SELECT * FROM commerce.__db000_grant_probe'
expect_denied support_app "$SUPPORT_APP_PASSWORD" \
  'CREATE TABLE support.__db000_forbidden (id integer)'
expect_denied commerce_app "$COMMERCE_APP_PASSWORD" \
  'CREATE TABLE commerce.__db000_forbidden (id integer)'

cleanup
trap - EXIT HUP INT TERM
psql_as support_owner "$SUPPORT_OWNER_PASSWORD" --file /db/tests/assert-catalog.sql

echo 'DB-000 grant matrix integration tests passed.'
